revert status check

diff --git a/.github/workflows/ci-matrix.yml b/.github/workflows/ci-matrix.yml
--- a/.github/workflows/ci-matrix.yml
+++ b/.github/workflows/ci-matrix.yml
@@ -75,8 +75,11 @@ jobs:
           retention-days: 1
 
   jupyter-book:
-    needs: execute
+    needs: executex
     runs-on: ubuntu-latest
+    # store success output flag for the ci job
+    outputs:
+      success: ${{ steps.setoutput.outputs.success }}
     env:
       PYTHON_VER: '3.11'
     steps:
@@ -107,21 +110,30 @@ jobs:
         uses: actions/upload-pages-artifact@v1
         with:
           path: docs/_build/html
+      - name: Set output flag
+        id: setoutput
+        run: echo "success=true" >> $GITHUB_OUTPUT
 
   # CI job for GitHub status check
-  # https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
+  # https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
   ci:
     name: CI (matrix)
-    needs: [setup, execute, jupyter-book]
-    if: ${{ always() }}
+    needs: jupyter-book
+    if: always()
     runs-on: ubuntu-latest
     steps:
-      - name: The job has succeeded
-        if: ${{ success() }}
-        run: exit 0
-      - name: The job has failed
-        if: ${{ failure() }}
-        run: exit 1
+      # pass step only when output of previous jupyter-book job is set
+      # in case at least one of the execution fails, jupyter-book is skipped
+      # and the output will not be set, which will then cause the ci job to fail
+      - run: |
+          passed="${{ needs.jupyter-book.outputs.success }}"
+          if [[ $passed == "true" ]]; then
+            echo "Tests passed"
+            exit 0
+          else
+            echo "Tests failed"
+            exit 1
+          fi
 
   # Deployment job
   deploy:
