new step for status check

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -1,4 +1,4 @@
-name: Build Docker Image and Jupyter Notebooks
+name: Build Docker Image and Run Jupyter Notebooks
 
 on:
   push:
@@ -20,7 +20,8 @@ jobs:
   docker:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
       - uses: docker/setup-buildx-action@v2
       - name: Build and cache Docker Image
         uses: docker/build-push-action@v3
@@ -34,14 +35,19 @@ jobs:
 
   execute:
     needs: docker
+    env:
+      JULIA_NUM_THREADS: 2
+      JUPYTER_TIMEOUT: 600
     strategy:
       fail-fast: false
       matrix:
+        # Notebooks need to be executed
         notebook:
           - plots
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
       - uses: docker/setup-buildx-action@v2
       - name: Load Docker Image
         uses: docker/build-push-action@v3
@@ -53,10 +59,11 @@ jobs:
           cache-from: type=gha
       - name: Execute Notebook
         run: >
-          docker run -v ${{ github.workspace }}:/work
+          docker run
+          -v ${{ github.workspace }}:/work
           -e JULIA_NUM_THREADS=${{ env.JULIA_NUM_THREADS }}
           ${{ env.IMAGE_NAME }}:test
-          jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute --inplace
+          jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=${{ env.JUPYTER_TIMEOUT }} --execute --inplace
           /work/docs/${{ matrix.notebook }}.ipynb
       - name: Upload Notebook
         uses: actions/upload-artifact@v3
@@ -67,6 +74,9 @@ jobs:
   jupyter-book:
     needs: execute
     runs-on: ubuntu-latest
+    # store success output flag for ci job
+    outputs:
+      success: ${{ steps.setoutput.outputs.success }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -74,7 +84,7 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: ${{ env.PYTHON_VER }}
-      - name: Install dependencies
+      - name: Install Jupyter Book
         run: pip install jupyter-book
       - run: mkdir -p out
       - name: Download notebooks
@@ -85,16 +95,42 @@ jobs:
         run: find out/ -type f -iname '*.ipynb' -exec mv -t docs/ {} +
       - name: Build website
         run: jupyter-book build docs/ -W -v
+      - name: Set output flag
+        id: setoutput
+        run: echo "::set-output name=success::true"
       - name: Setup Pages
+        if: github.ref == 'refs/heads/main'
         id: pages
         uses: actions/configure-pages@v2
       - name: Upload page artifact
+        if: github.ref == 'refs/heads/main'
         uses: actions/upload-pages-artifact@v1
         with:
           path: docs/_build/html
 
+  # This job is for GitHub status check
+  # https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
+  ci:
+    needs: [execute, jupyter-book]
+    runs-on: ubuntu-latest
+    if: always() # always run, so we never skip the check
+    steps:
+      # pass step only when output of previous jupyter-book job is set
+      # in case at least one of the execution fails, jupyter-book is skipped
+      # and the output will not be set, which will then cause the ci job to fail
+      - run: |
+          passed="${{ needs.jupyter-book.outputs.success }}"
+          if [[ $passed == "true" ]]; then
+            echo "Tests passed"
+            exit 0
+          else
+            echo "Tests failed"
+            exit 1
+          fi
+
+  # Push the docker image to the registry in case you want to download it
   docker-push:
-    needs: [execute, docker]
+    needs: [docker, execute]
     if: github.ref == 'refs/heads/main'
     runs-on: ubuntu-latest
     steps:
@@ -126,7 +162,7 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
-  # Deployment job
+  # Deploy GH pages
   deploy:
     needs: jupyter-book
     if: github.ref == 'refs/heads/main'
